AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild project for building docker image, tagging and pushing to ECR.'
Parameters:
  CodeBuildSourceS3Location:
    Type: String
    Description: 'S3 location for codebuild zip.'
  S3ECRRole:
    Type: String
    Description: 'ARN for role with access to S3 and ECR .'
  ECRName:
    Type: String
    Description: 'Name of docker repository.'
  ImageTag:
    Type: String
    Default: latest
    Description: 'Tag to use for image.'
  DeploymentName:
    Type: String
    Description: 'Name of deployment. Used in export names, and as tag for all resources.'
Resources:
  DockerBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      ServiceRole: !Ref S3ECRRole
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: IMAGE_REPO_NAME
            Value: !Ref ECRName
          - Name: IMAGE_TAG
            Value: !Ref ImageTag
      Source:
        Location: !Ref CodeBuildSourceS3Location
        Type: S3
      TimeoutInMinutes: 10
      Tags:
        - Key: 'DeploymentName'
          Value: !Ref DeploymentName
Outputs:
  CodeBuildProject:
    Description: 'Name of codebuild project for building and pushing docker image.'
    Value: !Ref DockerBuild
    Export:
      Name: !Sub '${DeploymentName}-${AWS::Region}-CodeBuildProject'
